#!/bin/bash

set -eux

pyvendir="$(dirname "$0")"

python="$(which python3 || which python)"

# FIXME: venvpool.py has moved.
exec "$python" "$pyvendir"/venvpool.py -l -- "$pyvendir"/pyven/initscripts.py "$@"
